<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Almacen extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Almacenmodel');
    } 

    /*
     * Listing of listaalmacen
     */
    function index()
    {
        $data['listaalmacen'] = $this->Almacenmodel->get_all_listaalmacen();

        $data['_view'] = 'almacen/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new almacen
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('centroMM','CentroMM','exact_length[4]|required');
		$this->form_validation->set_rules('idEmpleadoResponsable','IdEmpleadoResponsable');
		$this->form_validation->set_rules('nombre','Nombre','max_length[150]|required');
		$this->form_validation->set_rules('domicilio','Domicilio','max_length[150]|required');
		$this->form_validation->set_rules('idMunicipio','IdMunicipio','required');
		$this->form_validation->set_rules('telefono','Telefono','max_length[10]');
		$this->form_validation->set_rules('codigoPostal','CodigoPostal','exact_length[5]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'centroMM' => $this->input->post('centroMM'),
				'idEmpleadoResponsable' => $this->input->post('idEmpleadoResponsable'),
				'nombre' => $this->input->post('nombre'),
				'domicilio' => $this->input->post('domicilio'),
				'idMunicipio' => $this->input->post('idMunicipio'),
				'telefono' => $this->input->post('telefono'),
				'codigoPostal' => $this->input->post('codigoPostal'),
            );
            
            $almacen_id = $this->Almacenmodel->add_almacen($params);
            redirect('almacen/index');
        }
        else
        {
			$this->load->model('Empleadomodel');
			$data['all_listaempleado'] = $this->Empleadomodel->get_all_listaempleado();

			$this->load->model('Municipiomodel');
			$data['all_listamunicipio'] = $this->Municipiomodel->get_all_listamunicipio();
            
            $this->load->model('Comboboxesmodel');
            $data['estados'] = $this->Comboboxesmodel->getEstados();
            
            $data['_view'] = 'almacen/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a almacen
     */
    function edit($id)
    {   
        // check if the almacen exists before trying to edit it
        $data['almacen'] = $this->Almacenmodel->get_almacen($id);
        
        if(isset($data['almacen']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('centroMM','CentroMM','exact_length[4]|required');
			$this->form_validation->set_rules('idEmpleadoResponsable','IdEmpleadoResponsable');
			$this->form_validation->set_rules('nombre','Nombre','max_length[150]|required');
			$this->form_validation->set_rules('domicilio','Domicilio','max_length[150]|required');
			$this->form_validation->set_rules('idMunicipio','IdMunicipio','required');
			$this->form_validation->set_rules('telefono','Telefono','max_length[10]');
			$this->form_validation->set_rules('codigoPostal','CodigoPostal','exact_length[5]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'centroMM' => $this->input->post('centroMM'),
					'idEmpleadoResponsable' => $this->input->post('idEmpleadoResponsable'),
					'nombre' => $this->input->post('nombre'),
					'domicilio' => $this->input->post('domicilio'),
					'idMunicipio' => $this->input->post('idMunicipio'),
					'telefono' => $this->input->post('telefono'),
					'codigoPostal' => $this->input->post('codigoPostal'),
                );

                $this->Almacenmodel->update_almacen($id,$params);            
                redirect('almacen/index');
            }
            else
            {
				$this->load->model('Empleadomodel');
				$data['all_listaempleado'] = $this->Empleadomodel->get_all_listaempleado();

				$this->load->model('Municipiomodel');
				$data['all_listamunicipio'] = $this->Municipiomodel->get_all_listamunicipio();

                $this->load->model('Comboboxesmodel');
                $data['estados'] = $this->Comboboxesmodel->getEstados();

                $this->load->model('Almacenmodel');
				
				$idMunicipioSeleccionado = $this->Almacenmodel->obtenerIdMunicipio($id);
				$data['municipioSeleccionado'] = $idMunicipioSeleccionado;
				
				$data['estadoSeleccionado'] = $this->Almacenmodel->obtenerIdEstado($idMunicipioSeleccionado);
				

                $data['_view'] = 'almacen/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The almacen you are trying to edit does not exist.');
    } 

    /*
     * Deleting almacen
     */
    function remove($id)
    {
        $almacen = $this->Almacenmodel->get_almacen($id);

        // check if the almacen exists before trying to delete it
        if(isset($almacen['id']))
        {
            $this->Almacenmodel->delete_almacen($id);
            redirect('almacen/index');
        }
        else
            show_error('The almacen you are trying to delete does not exist.');
    }
    
}
