<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Autorizacion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Autorizacionmodel');
    }

    /*
     * Listing of autorizaciones
     */
    function index()
    {
        $data['listaAT'] = $this->Autorizacionmodel->get_all_listaautorizacion();
        $data['_view'] = 'autorizacion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new autorizacion
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('numero','Numero','max_length[20]|required');
        $this->form_validation->set_rules('año','Año','max_length[5]|required');
        $this->form_validation->set_rules('descripcion','Descripcion','max_length[200]|required');
        $this->form_validation->set_rules('descripcionDetallada','DescripcionDetallada','max_length[200]|required');
        $this->form_validation->set_rules('importe','Importe','max_length[50]|required');
        $this->form_validation->set_rules('fondo','Fondo','required');

        if($this->form_validation->run())
        {

            $importe = str_replace( ',', '', $this->input->post('importe'));

            $params = array(
                'numero' => $this->input->post('numero'),
                'año' => $this->input->post('año'),
                'descripcion' => $this->input->post('descripcion'),
                'descripcionDetallada' => $this->input->post('descripcionDetallada'),
                'importe' => $importe,
                'idFondo' => $this->input->post('fondo'),
            );

            $this->Autorizacionmodel->add_autorizacion($params);
            redirect('autorizacion/index');
        }
        else
        {
            $data['_view'] = 'autorizacion/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing an autorizacion
     */
    function edit($id)
    {
        $data['autorizacion'] = $this->Autorizacionmodel->get_autorizacion($id);

        if(isset($data['autorizacion']['id']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('numero','Numero','max_length[20]|required');
            $this->form_validation->set_rules('año','Año','max_length[5]|required');
            $this->form_validation->set_rules('descripcion','Descripcion','max_length[200]|required');
            $this->form_validation->set_rules('descripcionDetallada','DescripcionDetallada','max_length[200]|required');
            $this->form_validation->set_rules('importe','Importe','max_length[50]|required');
            $this->form_validation->set_rules('fondo','Fondo','required');

            if($this->form_validation->run())
            {
                $importe = str_replace( ',', '', $this->input->post('importe'));
                $params = array(
                    'numero' => $this->input->post('numero'),
                    'año' => $this->input->post('año'),
                    'descripcion' => $this->input->post('descripcion'),
                    'descripcionDetallada' => $this->input->post('descripcionDetallada'),
                    'importe' => $importe,
                    'idFondo' => $this->input->post('fondo'),
                );

                $this->Autorizacionmodel->update_autorizacion($id,$params);
                redirect('autorizacion/index');
            }
            else
            {
                $data['_view'] = 'autorizacion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('La autorización que está tratando de editar no existe.');
    }

    /*
     * Deleting autorizacion
     */
    function remove($id)
    {
        $autorizacion = $this->Autorizacionmodel->get_autorizacion($id);

        // check if the autorizacion exists before trying to delete it
        if(isset($autorizacion['id']))
        {
            $this->Autorizacionmodel->delete_autorizacion($id);
            redirect('autorizacion/index');
        }
        else
            show_error('La autorizacion que está tratando de eliminar no existe.');
    }

}
