<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Categoria extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Categoriamodel');
    } 

    /*
     * Listing of listacategoria
     */
    function index()
    {
        $data['listacategoria'] = $this->Categoriamodel->get_all_listacategoria();

        $data['_view'] = 'categoria/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new categoria
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','max_length[150]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
            );
            
            $categoria_id = $this->Categoriamodel->add_categoria($params);
            redirect('categoria/index');
        }
        else
        {            
            $data['_view'] = 'categoria/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a categoria
     */
    function edit($id)
    {   
        // check if the categoria exists before trying to edit it
        $data['categoria'] = $this->Categoriamodel->get_categoria($id);
        
        if(isset($data['categoria']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','max_length[150]|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
                );

                $this->Categoriamodel->update_categoria($id,$params);            
                redirect('categoria/index');
            }
            else
            {
                $data['_view'] = 'categoria/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The categoria you are trying to edit does not exist.');
    } 

    /*
     * Deleting categoria
     */
    function remove($id)
    {
        $categoria = $this->Categoriamodel->get_categoria($id);

        // check if the categoria exists before trying to delete it
        if(isset($categoria['id']))
        {
            $this->Categoriamodel->delete_categoria($id);
            redirect('categoria/index');
        }
        else
            show_error('The categoria you are trying to delete does not exist.');
    }
    
}
