<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Configuracion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Configuracionmodel');
    }

    /*
     * Listing of listacategoria
     */
    function index()
    {

        $data['_view'] = 'configuracion/index';
        $this->load->view('layouts/main',$data);
    }

    function updateDatos()
    {
        //1. Borrar los datos existentes en la tabla solcondetalle_tmp
        $this->Configuracionmodel->deleteTmpTable();

        //2. Obtener los datos actualizados
        $datosSolcon = $this->Configuracionmodel->get_solconupdate();

        //Si el arreglo datosSolcon no está vacio actualizar las tablas
        if (!empty($datosSolcon)) {
            $this->Configuracionmodel->updateSolcon($datosSolcon);
        }

    }

}