<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Configuracion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Configuracionmodel');
    }

    /*
     * Listing of listacategoria
     */
    function index()
    {
        $data['update'] = $this->Configuracionmodel->get_solconupdate();

        $data['_view'] = 'configuracion/index';
        $this->load->view('layouts/main',$data);
    }

}