<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Departamento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Departamentomodel');
    } 

    /*
     * Listing of listadepartamento
     */
    function index()
    {
        $data['listadepartamento'] = $this->Departamentomodel->get_all_listadepartamento();

        $data['_view'] = 'departamento/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new departamento
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','max_length[150]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
            );
            
            $departamento_id = $this->Departamentomodel->add_departamento($params);
            redirect('departamento/index');
        }
        else
        {            
            $data['_view'] = 'departamento/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a departamento
     */
    function edit($id)
    {   
        // check if the departamento exists before trying to edit it
        $data['departamento'] = $this->Departamentomodel->get_departamento($id);
        
        if(isset($data['departamento']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','max_length[150]|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
                );

                $this->Departamentomodel->update_departamento($id,$params);            
                redirect('departamento/index');
            }
            else
            {
                $data['_view'] = 'departamento/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The departamento you are trying to edit does not exist.');
    } 

    /*
     * Deleting departamento
     */
    function remove($id)
    {
        $departamento = $this->Departamentomodel->get_departamento($id);

        // check if the departamento exists before trying to delete it
        if(isset($departamento['id']))
        {
            $this->Departamentomodel->delete_departamento($id);
            redirect('departamento/index');
        }
        else
            show_error('The departamento you are trying to delete does not exist.');
    }
    
}
