<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Estado extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Estadomodel');
    } 

    /*
     * Listing of listaestado
     */
    function index()
    {
        $data['listaestado'] = $this->Estadomodel->get_all_listaestado();

        $data['_view'] = 'estado/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new estado
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','max_length[100]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
            );
            
            $estado_id = $this->Estadomodel->add_estado($params);
            redirect('estado/index');
        }
        else
        {            
            $data['_view'] = 'estado/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a estado
     */
    function edit($id)
    {   
        // check if the estado exists before trying to edit it
        $data['estado'] = $this->Estadomodel->get_estado($id);
        
        if(isset($data['estado']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','max_length[100]|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
                );

                $this->Estadomodel->update_estado($id,$params);            
                redirect('estado/index');
            }
            else
            {
                $data['_view'] = 'estado/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('El estado que está tratando de editar no existe.');
    } 

    /*
     * Deleting estado
     */
    function remove($id)
    {
        $estado = $this->Estadomodel->get_estado($id);

        // check if the estado exists before trying to delete it
        if(isset($estado['id']))
        {
            $this->Estadomodel->delete_estado($id);
            redirect('estado/index');
        }
        else
            show_error('El estado que está tratando de eliminar no existe.');
    }
    
}
