<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Familia extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Familiamodel');
    } 

    /*
     * Listing of listafamilia
     */
    function index()
    {
        $data['listafamilia'] = $this->Familiamodel->get_all_listafamilia();

        $data['_view'] = 'familia/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new familia
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('clave','Clave','max_length[20]|required');
		$this->form_validation->set_rules('descripcion','Descripcion','max_length[250]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'clave' => $this->input->post('clave'),
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $familia_id = $this->Familiamodel->add_familia($params);
            redirect('familia/index');
        }
        else
        {            
            $data['_view'] = 'familia/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a familia
     */
    function edit($id)
    {   
        // check if the familia exists before trying to edit it
        $data['familia'] = $this->Familiamodel->get_familia($id);
        
        if(isset($data['familia']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('clave','Clave','max_length[20]|required');
			$this->form_validation->set_rules('descripcion','Descripcion','max_length[250]|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'clave' => $this->input->post('clave'),
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Familiamodel->update_familia($id,$params);            
                redirect('familia/index');
            }
            else
            {
                $data['_view'] = 'familia/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The familia you are trying to edit does not exist.');
    } 

    /*
     * Deleting familia
     */
    function remove($id)
    {
        $familia = $this->Familiamodel->get_familia($id);

        // check if the familia exists before trying to delete it
        if(isset($familia['id']))
        {
            $this->Familiamodel->delete_familia($id);
            redirect('familia/index');
        }
        else
            show_error('The familia you are trying to delete does not exist.');
    }
    
}
