<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Formularioconsideracion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Formularioconsideracionmodel');
    } 

    /*
     * Listing of listaformularioconsideracion
     */
    function index()
    {
        $data['listaformularioconsideracion'] = $this->Formularioconsideracionmodel->get_all_listaformularioconsideracion();

        $data['_view'] = 'consideraciformularioconsideracion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new formularioconsideracion
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('fc1','Fc1','max_length[255]|required');
		$this->form_validation->set_rules('fc2','Fc2','max_length[255]|required');
		$this->form_validation->set_rules('fc3','Fc3','max_length[255]|required');
		$this->form_validation->set_rules('fc4','Fc4','max_length[255]|required');
		$this->form_validation->set_rules('fc5','Fc5','max_length[255]|required');
		$this->form_validation->set_rules('fc6','Fc6','max_length[255]|required');
		$this->form_validation->set_rules('fc7','Fc7','max_length[255]|required');
		$this->form_validation->set_rules('fc8','Fc8','max_length[255]|required');
		$this->form_validation->set_rules('fc9','Fc9','max_length[255]|required');
		$this->form_validation->set_rules('fc10','Fc10','max_length[255]|required');
		$this->form_validation->set_rules('fc11','Fc11','max_length[255]|required');
		$this->form_validation->set_rules('fc12','Fc12','max_length[255]|required');
		$this->form_validation->set_rules('fc13','Fc13','max_length[255]|required');
		$this->form_validation->set_rules('fc14','Fc14','max_length[255]|required');
		$this->form_validation->set_rules('fc15','Fc15','max_length[255]|required');
		$this->form_validation->set_rules('fc16','Fc16','max_length[255]|required');
		$this->form_validation->set_rules('fc17','Fc17','max_length[255]|required');
		$this->form_validation->set_rules('fc18','Fc18','max_length[255]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'fc1' => $this->input->post('fc1'),
				'fc2' => $this->input->post('fc2'),
				'fc3' => $this->input->post('fc3'),
				'fc4' => $this->input->post('fc4'),
				'fc5' => $this->input->post('fc5'),
				'fc6' => $this->input->post('fc6'),
				'fc7' => $this->input->post('fc7'),
				'fc8' => $this->input->post('fc8'),
				'fc9' => $this->input->post('fc9'),
				'fc10' => $this->input->post('fc10'),
				'fc11' => $this->input->post('fc11'),
				'fc12' => $this->input->post('fc12'),
				'fc13' => $this->input->post('fc13'),
				'fc14' => $this->input->post('fc14'),
				'fc15' => $this->input->post('fc15'),
				'fc16' => $this->input->post('fc16'),
				'fc17' => $this->input->post('fc17'),
				'fc18' => $this->input->post('fc18'),
            );
            
            $formularioconsideracion_id = $this->Formularioconsideracionmodel->add_formularioconsideracion($params);
            redirect('formularioconsideracion/index');
        }
        else
        {            
            $data['_view'] = 'consideraciformularioconsideracion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a formularioconsideracion
     */
    function edit($id)
    {   
        // check if the formularioconsideracion exists before trying to edit it
        $data['formularioconsideracion'] = $this->Formularioconsideracionmodel->get_formularioconsideracion($id);
        
        if(isset($data['formularioconsideracion']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('fc1','Fc1','max_length[255]|required');
			$this->form_validation->set_rules('fc2','Fc2','max_length[255]|required');
			$this->form_validation->set_rules('fc3','Fc3','max_length[255]|required');
			$this->form_validation->set_rules('fc4','Fc4','max_length[255]|required');
			$this->form_validation->set_rules('fc5','Fc5','max_length[255]|required');
			$this->form_validation->set_rules('fc6','Fc6','max_length[255]|required');
			$this->form_validation->set_rules('fc7','Fc7','max_length[255]|required');
			$this->form_validation->set_rules('fc8','Fc8','max_length[255]|required');
			$this->form_validation->set_rules('fc9','Fc9','max_length[255]|required');
			$this->form_validation->set_rules('fc10','Fc10','max_length[255]|required');
			$this->form_validation->set_rules('fc11','Fc11','max_length[255]|required');
			$this->form_validation->set_rules('fc12','Fc12','max_length[255]|required');
			$this->form_validation->set_rules('fc13','Fc13','max_length[255]|required');
			$this->form_validation->set_rules('fc14','Fc14','max_length[255]|required');
			$this->form_validation->set_rules('fc15','Fc15','max_length[255]|required');
			$this->form_validation->set_rules('fc16','Fc16','max_length[255]|required');
			$this->form_validation->set_rules('fc17','Fc17','max_length[255]|required');
			$this->form_validation->set_rules('fc18','Fc18','max_length[255]|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'fc1' => $this->input->post('fc1'),
					'fc2' => $this->input->post('fc2'),
					'fc3' => $this->input->post('fc3'),
					'fc4' => $this->input->post('fc4'),
					'fc5' => $this->input->post('fc5'),
					'fc6' => $this->input->post('fc6'),
					'fc7' => $this->input->post('fc7'),
					'fc8' => $this->input->post('fc8'),
					'fc9' => $this->input->post('fc9'),
					'fc10' => $this->input->post('fc10'),
					'fc11' => $this->input->post('fc11'),
					'fc12' => $this->input->post('fc12'),
					'fc13' => $this->input->post('fc13'),
					'fc14' => $this->input->post('fc14'),
					'fc15' => $this->input->post('fc15'),
					'fc16' => $this->input->post('fc16'),
					'fc17' => $this->input->post('fc17'),
					'fc18' => $this->input->post('fc18'),
                );

                $this->Formularioconsideracionmodel->update_formularioconsideracion($id,$params);            
                redirect('formularioconsideracion/index');
            }
            else
            {
                $data['_view'] = 'consideraciformularioconsideracion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The formularioconsideracion you are trying to edit does not exist.');
    } 

    /*
     * Deleting formularioconsideracion
     */
    function remove($id)
    {
        $formularioconsideracion = $this->Formularioconsideracionmodel->get_formularioconsideracion($id);

        // check if the formularioconsideracion exists before trying to delete it
        if(isset($formularioconsideracion['id']))
        {
            $this->Formularioconsideracionmodel->delete_formularioconsideracion($id);
            redirect('formularioconsideracion/index');
        }
        else
            show_error('The formularioconsideracion you are trying to delete does not exist.');
    }
    
}
