<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

 
class Generar_PDF extends CI_Controller{
    
    function __construct()
    {
        parent::__construct();
        $this->load->library('Pdf');
        $this->load->model('Generarpdfmodel');
    } 

    //PDF
    function pdf($id){
        $data['contactos'] = $this->Generarpdfmodel->get_contactos($id);
        $this->load->view('reporte_pog', $data);
        //Para probar los queries del modelo
        //$this->load->view('reporte_prueba_bd', $data);
    }
    
}

?>