<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Municipio extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Municipiomodel');
    } 

    /*
     * Listing of listamunicipio
     */
    function index()
    {
        $data['listamunicipio'] = $this->Municipiomodel->get_all_listamunicipio();

        $data['_view'] = 'municipio/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new municipio
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','max_length[100]|required');
		$this->form_validation->set_rules('idEstado','IdEstado','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idEstado' => $this->input->post('idEstado'),
				'nombre' => $this->input->post('nombre'),
            );
            
            $municipio_id = $this->Municipiomodel->add_municipio($params);
            redirect('municipio/index');
        }
        else
        {
			$this->load->model('Estadomodel');
			$data['all_listaestado'] = $this->Estadomodel->get_all_listaestado();
            
            $data['_view'] = 'municipio/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a municipio
     */
    function edit($id)
    {   
        // check if the municipio exists before trying to edit it
        $data['municipio'] = $this->Municipiomodel->get_municipio($id);
        
        if(isset($data['municipio']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','max_length[100]|required');
			$this->form_validation->set_rules('idEstado','IdEstado','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idEstado' => $this->input->post('idEstado'),
					'nombre' => $this->input->post('nombre'),
                );

                $this->Municipiomodel->update_municipio($id,$params);            
                redirect('municipio/index');
            }
            else
            {
				$this->load->model('Estadomodel');
				$data['all_listaestado'] = $this->Estadomodel->get_all_listaestado();

                $data['_view'] = 'municipio/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('El municipio que está tratando de editar no existe.');
    } 

    /*
     * Deleting municipio
     */
    function remove($id)
    {
        $municipio = $this->Municipiomodel->get_municipio($id);

        // check if the municipio exists before trying to delete it
        if(isset($municipio['id']))
        {
            $this->Municipiomodel->delete_municipio($id);
            redirect('municipio/index');
        }
        else
            show_error('El municipio que está tratando de eliminar no existe.');
    }
    
}
