<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Po_acuse extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Poacusemodel');
    } 

    /*
     * Listing of listapo_acuse
     */
    function index()
    {
        $data['listapo_acuse'] = $this->Poacusemodel->get_all_listapo_acuse();

        $data['_view'] = 'po_acuse/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new po_acuse
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $po_acuse_id = $this->Poacusemodel->add_po_acuse($params);
            redirect('po_acuse/index');
        }
        else
        {            
            $data['_view'] = 'po_acuse/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a po_acuse
     */
    function edit($idPog)
    {   
        // check if the po_acuse exists before trying to edit it
        $data['po_acuse'] = $this->Poacusemodel->get_po_acuse($idPog);
        
        if(isset($data['po_acuse']['idPog']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Poacusemodel->update_po_acuse($idPog,$params);            
                redirect('po_acuse/index');
            }
            else
            {
                $data['_view'] = 'po_acuse/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The po_acuse you are trying to edit does not exist.');
    } 

    /*
     * Deleting po_acuse
     */
    function remove($idPog)
    {
        $po_acuse = $this->Poacusemodel->get_po_acuse($idPog);

        // check if the po_acuse exists before trying to delete it
        if(isset($po_acuse['idPog']))
        {
            $this->Poacusemodel->delete_po_acuse($idPog);
            redirect('po_acuse/index');
        }
        else
            show_error('The po_acuse you are trying to delete does not exist.');
    }
    
}
