<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Po_proveedor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Poproveedormodel');
    } 

    /*
     * Listing of listapo_proveedor
     */
    function index()
    {
        $data['listapo_proveedor'] = $this->Poproveedormodel->get_all_listapo_proveedor();

        $data['_view'] = 'po_proveedor/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new po_proveedor
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('contacto','Contacto','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'contacto' => $this->input->post('contacto'),
            );
            
            $po_proveedor_id = $this->Poproveedormodel->add_po_proveedor($params);
            redirect('po_proveedor/index');
        }
        else
        {            
            $data['_view'] = 'po_proveedor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a po_proveedor
     */
    function edit($idPog)
    {   
        // check if the po_proveedor exists before trying to edit it
        $data['po_proveedor'] = $this->Poproveedormodel->get_po_proveedor($idPog);
        
        if(isset($data['po_proveedor']['idPog']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('contacto','Contacto','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'contacto' => $this->input->post('contacto'),
                );

                $this->Poproveedormodel->update_po_proveedor($idPog,$params);            
                redirect('po_proveedor/index');
            }
            else
            {
                $data['_view'] = 'po_proveedor/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The po_proveedor you are trying to edit does not exist.');
    } 

    /*
     * Deleting po_proveedor
     */
    function remove($idPog)
    {
        $po_proveedor = $this->Poproveedormodel->get_po_proveedor($idPog);

        // check if the po_proveedor exists before trying to delete it
        if(isset($po_proveedor['idPog']))
        {
            $this->Poproveedormodel->delete_po_proveedor($idPog);
            redirect('po_proveedor/index');
        }
        else
            show_error('The po_proveedor you are trying to delete does not exist.');
    }
    
}
