<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Relacionproveedorfamilia extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Relacionproveedorfamiliamodel');
    } 

    /*
     * Listing of listarelacionproveedorfamilia
     */
    function index()
    {
        $data['listarelacionproveedorfamilia'] = $this->Relacionproveedorfamiliamodel->get_all_listarelacionproveedorfamilia();

        $data['_view'] = 'relacionproveedorfamilia/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new relacionproveedorfamilia
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $relacionproveedorfamilia_id = $this->Relacionproveedorfamiliamodel->add_relacionproveedorfamilia($params);
            redirect('relacionproveedorfamilia/index');
        }
        else
        {            
            $data['_view'] = 'relacionproveedorfamilia/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a relacionproveedorfamilia
     */
    function edit($idProveedor)
    {   
        // check if the relacionproveedorfamilia exists before trying to edit it
        $data['relacionproveedorfamilia'] = $this->Relacionproveedorfamiliamodel->get_relacionproveedorfamilia($idProveedor);
        
        if(isset($data['relacionproveedorfamilia']['idProveedor']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Relacionproveedorfamiliamodel->update_relacionproveedorfamilia($idProveedor,$params);            
                redirect('relacionproveedorfamilia/index');
            }
            else
            {
                $data['_view'] = 'relacionproveedorfamilia/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The relacionproveedorfamilia you are trying to edit does not exist.');
    } 

    /*
     * Deleting relacionproveedorfamilia
     */
    function remove($idProveedor)
    {
        $relacionproveedorfamilia = $this->Relacionproveedorfamiliamodel->get_relacionproveedorfamilia($idProveedor);

        // check if the relacionproveedorfamilia exists before trying to delete it
        if(isset($relacionproveedorfamilia['idProveedor']))
        {
            $this->Relacionproveedorfamiliamodel->delete_relacionproveedorfamilia($idProveedor);
            redirect('relacionproveedorfamilia/index');
        }
        else
            show_error('The relacionproveedorfamilia you are trying to delete does not exist.');
    }
    
}
