<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Almacenmodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get almacen by id
     */
    function get_almacen($id)
    {
        return $this->db->get_where('almacen',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all listaalmacen
     */
    function get_all_listaalmacen()
    {
        return $this->db->get('almacen')->result_array();
    }
    
    /*
     * function to add new almacen
     */
	
	function add_almacen($params)
    {
		$params['id'] = $this->get_idConsecutivo();
        $this->db->insert('almacen',$params);
        return $this->db->insert_id();
    }
    
    function get_idConsecutivo()
    {
		$maxid = 1;
        $row = $this->db->query("select max(id) as 'maxid' from almacen")->row();
		if ($row) {
			$maxid = $row->maxid + 1;
		}
		return $maxid;
	}
    
    /*
     * function to update almacen
     */
    function update_almacen($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('almacen',$params);
        if($response)
        {
            return "almacen updated successfully";
        }
        else
        {
            return "Error occuring while updating almacen";
        }
    }
    
    /*
     * function to delete almacen
     */
    function delete_almacen($id)
    {
        $response = $this->db->delete('almacen',array('id'=>$id));
        if($response)
        {
            return "almacen deleted successfully";
        }
        else
        {
            return "Error occuring while deleting almacen";
        }
    }
}
