<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Categoriamodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categoria by id
     */
    function get_categoria($id)
    {
        return $this->db->get_where('categoria',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all listacategoria
     */
    function get_all_listacategoria()
    {
        return $this->db->get('categoria')->result_array();
    }
    
    /*
     * function to add new categoria
     */	
	    
	function add_categoria($params)
    {
		$params['id'] = $this->get_idConsecutivo();
        $this->db->insert('categoria',$params);
        return $this->db->insert_id();
    }
    
    function get_idConsecutivo()
    {
		$maxid = 1;
        $row = $this->db->query("select max(id) as 'maxid' from categoria")->row();
		if ($row) {
			$maxid = $row->maxid + 1;
		}
		return $maxid;
	}
    
    /*
     * function to update categoria
     */
    function update_categoria($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('categoria',$params);
        if($response)
        {
            return "Categoría actualizada existosamente";
        }
        else
        {
            return "Ocurrió un error al actualizar la categoría";
        }
    }
    
    /*
     * function to delete categoria
     */
    function delete_categoria($id)
    {
        $response = $this->db->delete('categoria',array('id'=>$id));
        if($response)
        {
            return "Categoría eliminada exitosamente";
        }
        else
        {
            return "Ocurrió un error al actualizar la categoría";
        }
    }
}
