<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Departamentomodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get departamento by id
     */
    function get_departamento($id)
    {
        return $this->db->get_where('departamento',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all listadepartamento
     */
    function get_all_listadepartamento()
    {
        return $this->db->get('departamento')->result_array();
    }
    
    /*
     * function to add new departamento
     */
    function add_departamento($params)
    {
        $this->db->insert('departamento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update departamento
     */
    function update_departamento($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('departamento',$params);
        if($response)
        {
            return "departamento updated successfully";
        }
        else
        {
            return "Error occuring while updating departamento";
        }
    }
    
    /*
     * function to delete departamento
     */
    function delete_departamento($id)
    {
        $response = $this->db->delete('departamento',array('id'=>$id));
        if($response)
        {
            return "departamento deleted successfully";
        }
        else
        {
            return "Error occuring while deleting departamento";
        }
    }
}
