<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Embalajemodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get embalaje by id
     */
    function get_embalaje($id)
    {
        return $this->db->get_where('embalaje',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all listaembalaje
     */
    function get_all_listaembalaje()
    {
        return $this->db->get('embalaje')->result_array();
    }
    
    /*
     * function to add new embalaje
     */
	
	function add_embalaje($params)
    {
		$params['id'] = $this->get_idConsecutivo();
        $this->db->insert('embalaje',$params);
        return $this->db->insert_id();
    }
    
    function get_idConsecutivo()
    {
		$maxid = 1;
        $row = $this->db->query("select max(id) as 'maxid' from embalaje")->row();
		if ($row) {
			$maxid = $row->maxid + 1;
		}
		return $maxid;
	}
    
    /*
     * function to update embalaje
     */
    function update_embalaje($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('embalaje',$params);
        if($response)
        {
            return "embalaje updated successfully";
        }
        else
        {
            return "Error occuring while updating embalaje";
        }
    }
    
    /*
     * function to delete embalaje
     */
    function delete_embalaje($id)
    {
        $response = $this->db->delete('embalaje',array('id'=>$id));
        if($response)
        {
            return "embalaje deleted successfully";
        }
        else
        {
            return "Error occuring while deleting embalaje";
        }
    }
}
