<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Familiamodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get familia by id
     */
    function get_familia($id)
    {
        return $this->db->get_where('familia',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all listafamilia
     */
    function get_all_listafamilia()
    {
        return $this->db->get('familia')->result_array();
    }
    
    /*
     * function to add new familia
     */
	
	function add_familia($params)
    {
		$params['id'] = $this->get_idConsecutivo();
        $this->db->insert('familia',$params);
        return $this->db->insert_id();
    }
    
    function get_idConsecutivo()
    {
		$maxid = 1;
        $row = $this->db->query("select max(id) as 'maxid' from familia")->row();
		if ($row) {
			$maxid = $row->maxid + 1;
		}
		return $maxid;
	}
    
    /*
     * function to update familia
     */
    function update_familia($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('familia',$params);
        if($response)
        {
            return "Familia actualizada exitosamente";
        }
        else
        {
            return "Ocurrió un error al actualizar la familia";
        }
    }
    
    /*
     * function to delete familia
     */
    function delete_familia($id)
    {
        $response = $this->db->delete('familia',array('id'=>$id));
        if($response)
        {
            return "Familia eliminada exitosamente";
        }
        else
        {
            return "Ocurrió un error al actualizar la familia";
        }
    }
}
