<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Imconceptomodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get im_concepto by id
     */
    function get_im_concepto($id)
    {
        return $this->db->get_where('im_concepto',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all listaim_concepto
     */
    function get_all_listaim_concepto()
    {
        return $this->db->get('im_concepto')->result_array();
    }
    
    /*
     * function to add new im_concepto
     */
	
	function add_im_concepto($params)
    {
		$params['id'] = $this->get_idConsecutivo();
        $this->db->insert('im_concepto',$params);
        return $this->db->insert_id();
    }
    
    function get_idConsecutivo()
    {
		$maxid = 1;
        $row = $this->db->query("select max(id) as 'maxid' from im_concepto")->row();
		if ($row) {
			$maxid = $row->maxid + 1;
		}
		return $maxid;
	}
    
    /*
     * function to update im_concepto
     */
    function update_im_concepto($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('im_concepto',$params);
        if($response)
        {
            return "im_concepto updated successfully";
        }
        else
        {
            return "Error occuring while updating im_concepto";
        }
    }
    
    /*
     * function to delete im_concepto
     */
    function delete_im_concepto($id)
    {
        $response = $this->db->delete('im_concepto',array('id'=>$id));
        if($response)
        {
            return "im_concepto deleted successfully";
        }
        else
        {
            return "Error occuring while deleting im_concepto";
        }
    }
}
