<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Imgeneraltemporal extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get im_general by id
     */
    
}
