<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Imgeneralmodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get im_general by id
     */
    function get_im_general($id)
    {
        return $this->db->get_where('im_general',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all listaim_general
     */
    function get_all_listaim_general()
    {
        return $this->db->get('im_general')->result_array();
    }
    
    /*
     * function to add new im_general
     */
    function add_im_general($params)
    {
        $this->db->insert('im_general',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update im_general
     */
    function update_im_general($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('im_general',$params);
        if($response)
        {
            return "im_general updated successfully";
        }
        else
        {
            return "Error occuring while updating im_general";
        }
    }
    
    /*
     * function to delete im_general
     */
    function delete_im_general($id)
    {
        $response = $this->db->delete('im_general',array('id'=>$id));
        if($response)
        {
            return "im_general deleted successfully";
        }
        else
        {
            return "Error occuring while deleting im_general";
        }
    }
}
