<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Poaclaracionmodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get po_aclaracion by idPog
     */
    function get_po_aclaracion($idPog)
    {
        return $this->db->get_where('po_aclaracion',array('idPog'=>$idPog))->row_array();
    }
    
    /*
     * Get all listapo_aclaracion
     */
    function get_all_listapo_aclaracion()
    {
        return $this->db->get('po_aclaracion')->result_array();
    }
    
    /*
     * function to add new po_aclaracion
     */
    function add_po_aclaracion($params)
    {
		$params['id'] = $this->get_idConsecutivo();
        $this->db->insert('po_aclaracion',$params);
        return $this->db->insert_id();
    }
    
    function get_idConsecutivo()
    {
		$maxid = 1;
        $row = $this->db->query("select max(id) as 'maxid' from po_aclaracion")->row();
		if ($row) {
			$maxid = $row->maxid + 1;
		}
		return $maxid;
	}
    
    /*
     * function to update po_aclaracion
     */
    function update_po_aclaracion($idPog,$params)
    {
        $this->db->where('idPog',$idPog);
        $response = $this->db->update('po_aclaracion',$params);
        if($response)
        {
            return "po_aclaracion updated successfully";
        }
        else
        {
            return "Error occuring while updating po_aclaracion";
        }
    }
    
    /*
     * function to delete po_aclaracion
     */
    function delete_po_aclaracion($idPog)
    {
        $response = $this->db->delete('po_aclaracion',array('idPog'=>$idPog));
        if($response)
        {
            return "po_aclaracion deleted successfully";
        }
        else
        {
            return "Error occuring while deleting po_aclaracion";
        }
    }
}
