<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Poconsideracionmodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get po_consideracion by id
     */
    function get_po_consideracion($id)
    {
        return $this->db->get_where('po_consideracion',array('id'=>$id))->row_array();
    }

    
    /*
     * Get all listapo_consideracion
     */
    function get_all_listapo_consideracion()
    {
        return $this->db->get('po_consideracion')->result_array();
    }
    
    /*
     * function to add new po_consideracion
     */
	
	function add_po_consideracion($params)
    {
		$params['id'] = $this->get_idConsecutivo();
        $this->db->insert('po_consideracion',$params);
        return $this->db->insert_id();
    }
    
    function get_idConsecutivo()
    {
		$maxid = 1;
        $row = $this->db->query("select max(id) as 'maxid' from po_consideracion")->row();
		if ($row) {
			$maxid = $row->maxid + 1;
		}
		return $maxid;
	}
    
    /*
     * function to update po_consideracion
     */
    function update_po_consideracion($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('po_consideracion',$params);
        if($response)
        {
            return "po_consideracion updated successfully";
        }
        else
        {
            return "Error occuring while updating po_consideracion";
        }
    }
    
    /*
     * function to delete po_consideracion
     */
    function delete_po_consideracion($id)
    {
        $response = $this->db->delete('po_consideracion',array('id'=>$id));
        if($response)
        {
            return "po_consideracion deleted successfully";
        }
        else
        {
            return "Error occuring while deleting po_consideracion";
        }
    }
}
