<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Relacionproveedorfamiliamodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get relacionproveedorfamilia by idProveedor
     */
    function get_relacionproveedorfamilia($idProveedor)
    {
        return $this->db->get_where('relacionproveedorfamilia',array('idProveedor'=>$idProveedor))->row_array();
    }
    
    /*
     * Get all listarelacionproveedorfamilia
     */
    function get_all_listarelacionproveedorfamilia()
    {
        //return $this->db->get('relacionproveedorfamilia')->result_array();
        $this->db->select('proveedor.razonSocial, familia.clave');
        $this->db->from('relacionproveedorfamilia');
        $this->db->join('proveedor', 'proveedor.id = relacionproveedorfamilia.idProveedor', 'inner');
        $this->db->join('familia', 'familia.id = relacionproveedorfamilia.idFamilia', 'inner');
        $query = $this->db->get();
        return $query->result_array();
    }
    
    /*
     * function to add new relacionproveedorfamilia
     */
	
	function add_relacionproveedorfamilia($params)
    {
		$params['id'] = $this->get_idConsecutivo();
        $this->db->insert('relacionproveedorfamilia',$params);
        return $this->db->insert_id();
    }
    
    function get_idConsecutivo()
    {
		$maxid = 1;
        $row = $this->db->query("select max(id) as 'maxid' from relacionproveedorfamilia")->row();
		if ($row) {
			$maxid = $row->maxid + 1;
		}
		return $maxid;
	}
    
    /*
     * function to update relacionproveedorfamilia
     */
    function update_relacionproveedorfamilia($idProveedor,$params)
    {
        $this->db->where('idProveedor',$idProveedor);
        $response = $this->db->update('relacionproveedorfamilia',$params);
        if($response)
        {
            return "relacionproveedorfamilia updated successfully";
        }
        else
        {
            return "Error occuring while updating relacionproveedorfamilia";
        }
    }
    
    /*
     * function to delete relacionproveedorfamilia
     */
    function delete_relacionproveedorfamilia($idProveedor)
    {
        $response = $this->db->delete('relacionproveedorfamilia',array('idProveedor'=>$idProveedor));
        if($response)
        {
            return "relacionproveedorfamilia deleted successfully";
        }
        else
        {
            return "Error occuring while deleting relacionproveedorfamilia";
        }
    }
}
