<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Relacionproveedorfamiliamodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get relacionproveedorfamilia by idProveedor
     */
    function get_relacionproveedorfamilia($idProveedor)
    {
        return $this->db->get_where('relacionproveedorfamilia',array('idProveedor'=>$idProveedor))->row_array();
    }
    
    /*
     * Get all listarelacionproveedorfamilia
     */
    function get_all_listarelacionproveedorfamilia()
    {
        return $this->db->get('relacionproveedorfamilia')->result_array();
    }
    
    /*
     * function to add new relacionproveedorfamilia
     */
    function add_relacionproveedorfamilia($params)
    {
        $this->db->insert('relacionproveedorfamilia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update relacionproveedorfamilia
     */
    function update_relacionproveedorfamilia($idProveedor,$params)
    {
        $this->db->where('idProveedor',$idProveedor);
        $response = $this->db->update('relacionproveedorfamilia',$params);
        if($response)
        {
            return "relacionproveedorfamilia updated successfully";
        }
        else
        {
            return "Error occuring while updating relacionproveedorfamilia";
        }
    }
    
    /*
     * function to delete relacionproveedorfamilia
     */
    function delete_relacionproveedorfamilia($idProveedor)
    {
        $response = $this->db->delete('relacionproveedorfamilia',array('idProveedor'=>$idProveedor));
        if($response)
        {
            return "relacionproveedorfamilia deleted successfully";
        }
        else
        {
            return "Error occuring while deleting relacionproveedorfamilia";
        }
    }
}
