<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Unidadmedidamodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unidadmedida by id
     */
    function get_unidadmedida($id)
    {
        return $this->db->get_where('unidadmedida',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all listaunidadmedida
     */
    function get_all_listaunidadmedida()
    {
        return $this->db->get('unidadmedida')->result_array();
    }
    
    /*
     * function to add new unidadmedida
     */
    function add_unidadmedida($params)
    {
        $this->db->insert('unidadmedida',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unidadmedida
     */
    function update_unidadmedida($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('unidadmedida',$params);
        if($response)
        {
            return "unidadmedida updated successfully";
        }
        else
        {
            return "Error occuring while updating unidadmedida";
        }
    }
    
    /*
     * function to delete unidadmedida
     */
    function delete_unidadmedida($id)
    {
        $response = $this->db->delete('unidadmedida',array('id'=>$id));
        if($response)
        {
            return "unidadmedida deleted successfully";
        }
        else
        {
            return "Error occuring while deleting unidadmedida";
        }
    }
}
