<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Unidadmedidamodel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unidadmedida by id
     */
    function get_unidadmedida($id)
    {
        return $this->db->get_where('unidadmedida',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all listaunidadmedida
     */
    function get_all_listaunidadmedida()
    {
        return $this->db->get('unidadmedida')->result_array();
    }
    
    /*
     * function to add new unidadmedida
     */
	
	function add_unidadmedida($params)
    {
		$params['id'] = $this->get_idConsecutivo();
        $this->db->insert('unidadmedida',$params);
        return $this->db->insert_id();
    }
    
    function get_idConsecutivo()
    {
		$maxid = 1;
        $row = $this->db->query("select max(id) as 'maxid' from unidadmedida")->row();
		if ($row) {
			$maxid = $row->maxid + 1;
		}
		return $maxid;
	}
    
    /*
     * function to update unidadmedida
     */
    function update_unidadmedida($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('unidadmedida',$params);
        if($response)
        {
            return "Unidad de medida actualizada exitosamente";
        }
        else
        {
            return "Ocurrió un error al actualizar la unidad de medida";
        }
    }
    
    /*
     * function to delete unidadmedida
     */
    function delete_unidadmedida($id)
    {
        $response = $this->db->delete('unidadmedida',array('id'=>$id));
        if($response)
        {
            return "Unidad de medida eliminada exitosamente";
        }
        else
        {
            return "Ocurrió un error al eliminar la unidad de medida";
        }
    }
}
